name: Backend Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setting up JDK (Java Development Kit)
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'temurin'

     # granting permissions to the Maven wrapper
        
      - name: Grant execute permission for Maven wrapper
        run: chmod +x backend/mvnw

      # Installing dependencies and build the project
      - name: Build with Maven
        run: |
          cd backend
          ./mvnw clean install -DskipTests

      # Running tests 
      - name: Run tests
        run: |
          cd backend
          ./mvnw test

      # Packaging the Spring Boot app
      - name: Package Spring Boot app
        run: |
          cd backend
          ./mvnw clean package -DskipTests
