name: Frontend Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setting up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      # Installing dependencies
      - name: Install dependencies
        run: |
          cd frontend
          npm install


      # Building the React app
      - name: Build React app
        run: |
          cd frontend
          npm run build
